### ISSUE TITLE
Having trouble with Add Event Listener to an element id 

### ISSUE THREAD

**Issue by bfellerath** [bfellerath/TicTacToe#2]
## UserStory

-As a user, I want to be able to click on where I want to make a move so I can can interact with the game to beat friends.
## Test Statement

-When I click on the node it should change according to my if statements
## Context

-When I'm trying to do this thing, I got it working for one <td> node on the table but I changed the name of the ids in order to add event listeners to more nodes and I haven't been able to get it working.
-I have tried using javascript and jquery to traverse the dom
-What triggers the bug or how can we reproduce the bug... It isn't really a bug, just having trouble getting the event listener to work for the various nodes in my game board.

Here is the code I am working on right now: 

```
window.onload = function() {
function modifyText() {
  var t2 = document.getElementById("t2");
  if (t2.firstChild.nodeValue == "null") {
    t2.firstChild.nodeValue = "x";
  } else {
    t2.firstChild.nodeValue = "null";
  }
}


// add event listener to table



var el = document.getElementById("t2");
el.addEventListener("click", modifyText, false);
```

**Comment by iiVi** [comment]
Helped in person.
