### ISSUE TITLE
Working on getting a row and column number from a click, this.attr not working

### ISSUE THREAD

**Issue by bfellerath** [bfellerath/TicTacToe#3]
## UserStory

-As a user, I want to be able to have my clicks effect the actual game, so I can know I am playing an actual game and not just clicking on things that turn into other things.
## Test Statement

-when I click on the elements, it should make a change in the game state as well. I will do this by getting the number location of the click (two numbers, row and column) from that event.
## Context

-When I'm trying to get these numbers with this.attr('row')
-I have tried using this.val as well and it keeps saying this.attr or this.val is not a function
-What triggers the bug or how can we reproduce the bug... What is strange to me is I was just using this.innerHTML to change the text and that works fine.
### Error Message

```
Uncaught TypeError: this.attr is not a function
```

**Comment by amadden80** [comment]
I see two issues here.

##First:
One is that your 'this' is not a jquery this.
Consider $(this) to solve that issue.

##Second:
My suggestion is you change to using data attriubtes.  .attr only works for some (as I understand).

Consider this:

```
<h2 data-row='2'></h2>
```

```
$('h2').data('row');  //  '2'
```

**Comment by bfellerath** [comment]
I did the first part and that worked. Now I have the numbers I need. I am working on how to call these variables with another function. Here is what my modifyText function looks like right now:

```
  function modifyText() {

        if (this.innerHTML === "null") {

          //Not sure why this line is not working

          this.innerHTML = 'x';
          console.log(this);
        this.row = $(this).attr('row');
        this.column = $(this).attr('column');
        makeMove(this.row, this.column);

        console.log('row = ' + this.row);
        console.log('column = ' + this.column);

          //var column = this.attr('column');
        //  console.log(row);
        }   else {
          alert ('please choose an open square');
        }
      };

```

**Comment by amadden80** [comment]
``` js
  function modifyText() {

        if (this.innerHTML === "null") {

          //Not sure why this line is not working

          this.innerHTML = 'x';
          console.log(this);
        this.row = $(this).data('row');
        this.column = $(this).data('column');
        makeMove(this.row, this.column);

        console.log('row = ' + this.row);
        console.log('column = ' + this.column);

          //var column = this.data('column');
        //  console.log(row);
        }   else {
          alert ('please choose an open square');
        }
      };
```

You mean like that?

**Comment by emilylordahl** [comment]
Made progress!
