### ISSUE TITLE
resetGame function

### ISSUE THREAD

**Issue by bfellerath** [bfellerath/TicTacToe#4]
## UserStory

-As a user, I want to be able to have the game reset when there is a winner, so I can get started on a new game.
## Test Statement

in a reset game function, the original gameState should be returned
## Context

-When I'm trying to reset the game to its original gameState
-I have tried several ways of saying that the game now = the original gameState
-What triggers the bug or how can we reproduce the bug, play through game, even though game reset fires, the game doesn't reset.
### gameReset

```
function gameReset (board){

  this.board = gameState;
  console.log('game reset fired');
  return this.board;
  }
```

**Comment by emilylordahl** [comment]
What is the `gameState` at the beginning of a game? Perhaps you can reset it to that state. Or create a `new` game! Does that help?

**Comment by bfellerath** [comment]
The gameState at the beginning is an array of nulls in every cell position. I am trying to create a new game and it is getting me closer.

**Comment by emilylordahl** [comment]
Sweet!
